fix(BlockHeader): refactoring
gravity-ui/page-constructor pull request #105
Opened 2023-01-10 06:29 UTC by yuberdysheva

2023-01-10 09:16 UTC, niktverd commented on src/components/HeaderComponent/__stories__/HeaderComponent.stories.tsx
> +import React from 'react';
Above local imports

2023-01-11 09:09 UTC, gorgeousvlad requested changes

2023-01-11 09:09 UTC, gorgeousvlad commented on src/text-transform/blocks.ts
> +    [BlockType.PromoFeaturesBlock]: [
```
const blockHeaderTransfomer =  [
       {
            fields: ['title'],
            transformer: typografTransformer,
            parser: parseTitle,
        },
        {
            fields: ['description'],
            transformer: yfmTransformer,
        }
];
```

2023-01-11 09:14 UTC, yuberdysheva commented on src/blocks/CardLayout/CardLayout.tsx
> +import {HeaderComponent, AnimateBlock} from '../../components';
For me it is confusing that we have `HeaderBlock` and `BlockHeader`. I thought that `HeaderBlock` and `HeaderComponent` more understandable. How `BlockHeader` tells about purpose?

2023-01-11 11:37 UTC, gorgeousvlad commented on src/blocks/CardLayout/CardLayout.tsx
> +import {HeaderComponent, AnimateBlock} from '../../components';
`BlockHeader` tells that it is using for heading in blocks, `HeaderComponent` not, but raises questions - why do we have both component and block headers? 
And `HeaderComponent` has extra info in its name - we import it form `components` dir and it is clear that it is a component. And in this case should we add `Component` prefix to any component?

For to make things clear with this renaming we could exclude 'header' and use `BlockTitle` or something like that.

Anyway, we can leave this renaming for major update - it doesn't worth major with itself.

2023-01-11 11:51 UTC, yuberdysheva commented on src/blocks/CardLayout/CardLayout.tsx
> +import {HeaderComponent, AnimateBlock} from '../../components';
I like BlockTitle, let's leave this for major update. Thanks

2023-01-11 12:17 UTC, gorgeousvlad approved these changes

2023-01-11 12:18 UTC, niktverd approved these changes

2023-01-11 12:19 UTC, merged