Add youtube to card with image
gravity-ui/page-constructor pull request #126
Opened 2023-02-01 06:54 UTC by gorgeousvlad

2023-02-01 07:04 UTC, gorgeousvlad commented
Preview:

https://preview.gravity-ui.com/page-constructor/126/?path=/story/components-cards-mediacard--full-screen

2023-02-01 08:52 UTC, NikitaCG commented on src/components/FullscreenMedia/FullScreenMedia.tsx
> +                    <Icon data={FullScreen} width={18} height={18} className={b('icon')} />
we can use constant like `ICON_SIZE` for these dimensions

2023-02-01 09:05 UTC, NikitaCG commented on src/components/FullscreenMedia/FullScreenMedia.tsx
> +    const hideFullScreenIcon = useCallback(() => setIsMouseEnter(false), []);
we can not use useCallback, because here it will not give a performance boost in this component

2023-02-01 09:54 UTC, gorgeousvlad commented on src/sub-blocks/MediaCard/MediaCard.tsx
> +    return !(dataLens || Array.isArray(image));
unfortunately no

https://github.com/gravity-ui/page-constructor/blob/33652d826fe56b29aaa6d19afd056a404cebcfc1/src/components/Media/Image/Image.tsx#L90

2023-02-01 09:56 UTC, NikitaCG approved these changes

2023-02-01 12:58 UTC, NikitaCG requested changes
still useCallback in FullScreenMedia

2023-02-01 13:22 UTC, yuberdysheva commented
Can you add story for CardWithMedia with youtube and fullscreen, please?

2023-02-01 13:32 UTC, gorgeousvlad commented
> Can you add story for CardWithMedia with youtube and fullscreen, please?

it is here:

<img width="1629" alt="Screen Shot 2023-02-01 at 17 30 29" src="https://user-images.githubusercontent.com/20395936/216057082-6aef74ee-eb0a-4d66-a25e-0caccba68b9e.png">

2023-02-01 13:38 UTC, NikitaCG approved these changes

2023-02-01 15:09 UTC, NikitaCG commented on src/components/FullscreenMedia/FullScreenMedia.tsx
> +                    <Icon data={FullScreen} width={18} height={18} className={b('icon')} />
ping

2023-02-01 15:11 UTC, yuberdysheva requested changes

2023-02-02 15:34 UTC, yuberdysheva requested changes
Let

2023-02-02 15:34 UTC, yuberdysheva commented on src/sub-blocks/Content/Content.tsx
> +            {metaInfo && (
metaInfo should be in CardWithImage

2023-02-03 13:59 UTC, yuberdysheva approved these changes

2023-02-05 07:57 UTC, merged