feat: add Map-block
gravity-ui/page-constructor pull request #149
Opened 2023-02-14 09:02 UTC by Lakate

2023-02-15 13:47 UTC, aeksandla requested changes

2023-02-15 13:47 UTC, aeksandla commented on src/blocks/Map/__stories__/data.json
> +        "text": "Button\r",
'\r' is unnecessary

2023-02-15 13:47 UTC, aeksandla commented on src/blocks/Map/__stories__/data.json
> +        "address": "Москва Арбат",
Can we write it in english?

2023-02-15 13:47 UTC, aeksandla commented on src/components/Map/Map.scss
> +$block: '.#{$ns}Map';
we write the class names in kebab-case

2023-02-15 13:47 UTC, aeksandla commented on src/components/Map/__stories__/ApiKeyInput.tsx
> +            <input
can we use TextInput from ui-kit?
https://preview.gravity-ui.com/uikit/?path=/story/components-textinput--default

2023-02-15 13:47 UTC, aeksandla commented on src/components/Map/__stories__/data.json
> +          "iconContent": "Красная площадь"
Can we write it in english?

2023-02-15 14:34 UTC, gorgeousvlad requested changes

2023-02-15 14:34 UTC, gorgeousvlad commented on src/components/Map/YandexMapHelpers.ts
> +export function initMap(containerId: string, initParams?: IInitMapParams) {
are we sure we won't call it on server?

2023-02-15 14:34 UTC, gorgeousvlad commented on src/components/Map/YandexMapHelpers.ts
> +
it is not used anywhere, I think it needs to be commented

2023-02-15 14:34 UTC, gorgeousvlad commented on src/components/Map/YandexMapHelpers.ts
> +            : loadScript(src, {id: `ymaps-script`}).then(() => {
create a constant for id pls

2023-02-15 14:34 UTC, gorgeousvlad commented on src/components/Map/YandexMapHelpers.ts
> +        if (YMapsApiLoader.loaders.length !== 0) {
Didn't really understand - if we need to load y maps only one time why do we need this loaders query and if we need to load it many times simultaneously then why we use this static methods only class and not use just class instance for each load?

2023-02-15 14:34 UTC, gorgeousvlad commented on src/components/Map/YandexMapHelpers.ts
> +export class YMap {
I think it would be better to have different files for different classes

2023-02-15 14:34 UTC, gorgeousvlad commented on src/components/Map/YandexMapHelpers.ts
> +            : loadScript(src, {id: `ymaps-script`}).then(() => {
is it ok not to using `catch` here?

2023-02-15 14:34 UTC, gorgeousvlad commented on src/components/Map/YandexMapHelpers.ts
> +        const res = await window.ymaps.geocode(marker.address, {results: 1});
is it okay not to use `catch`?

2023-02-15 14:34 UTC, gorgeousvlad commented on src/components/Map/YandexMapHelpers.ts
> +        if (iconCaption) {
could we generalize these ifs?

2023-02-15 14:34 UTC, gorgeousvlad commented on src/components/Map/YandexMapHelpers.ts
> +        if (!coordsLength) return;
we try not to use one string ifs

2023-02-15 14:34 UTC, gorgeousvlad commented on src/containers/PageConstructor/Provider.tsx
> +        <MapsValueContext.Provider value={mapsContext} />,
why do we need two contexts for maps, not one?

2023-02-15 14:34 UTC, gorgeousvlad commented on src/context/mapsContext/mapsProvider.tsx
> +export class MapProvider extends React.Component<
we are trying to use only functional react components

2023-02-15 15:49 UTC, yuberdysheva requested changes

2023-02-15 15:49 UTC, yuberdysheva commented on src/context/mapsContext/mapsProvider.tsx
> +    componentDidMount() {
Can we use React hook here?

2023-02-15 15:59 UTC, yuberdysheva commented
Is storybook maps don't rerender height between tabs. Only when we reload page
![image](https://user-images.githubusercontent.com/22456330/219081855-54e18edb-3bdd-4704-a7b5-075857740c54.png)

2023-02-20 12:02 UTC, Lakate commented on src/components/Map/YandexMap.tsx
> +        const updateSize = _.debounce(() => {
yep, for example when we change a browser window size

2023-02-21 13:51 UTC, Lakate commented
I have changed the work with maps:
1) you have to pass scriptSrc to the mapsContext
2) i created a helper file in storybook to store maps constants to use it in the stories only
After all, i don't see any constants connected with yandex maps api in build. (the YandexMap component left in the builded files)

2023-02-22 12:10 UTC, gorgeousvlad approved these changes

2023-02-27 07:39 UTC, yuberdysheva commented on src/components/Map/Map.scss
> +    height: 300px;
I see that max-height below is also 300px, maybe we need a constant here?

2023-02-27 07:41 UTC, yuberdysheva approved these changes

2023-02-27 11:23 UTC, aeksandla approved these changes

2023-02-28 13:15 UTC, merged