feat: map-block parameter for disable auto zoom
gravity-ui/page-constructor pull request #219
Opened 2023-03-16 20:22 UTC by Lakate

2023-03-17 08:05 UTC, gorgeousvlad approved these changes

2023-03-21 12:19 UTC, Lakate commented
Some changes:
1) delete center from params - we always calculate it in the code. We show the Yandex map after calculating the center
2) zoom - if you specify it in the parameters, we use it, if not, then we calculate it in the code

2023-03-22 16:18 UTC, gorgeousvlad requested changes

2023-03-22 16:18 UTC, gorgeousvlad commented on src/components/Map/GoogleMap.tsx
> +    zoom?: number,
to many serial params in function let's rewrite to object

2023-03-22 16:18 UTC, gorgeousvlad commented on src/components/Map/GoogleMap.tsx
> +    lang: 'ru' | 'en',
do we already had enum for Lang?

2023-03-22 16:18 UTC, gorgeousvlad commented on src/components/Map/Map.scss
> +    &_visible_no {
can we replace `visible_no` to `hidden`?

2023-03-22 16:18 UTC, gorgeousvlad commented on src/components/Map/YMap/YMap.ts
> +        const {zoom} = props;
const {zoom=0} = props;

2023-03-22 16:18 UTC, gorgeousvlad commented on src/components/Map/YMap/YMap.ts
> +            newMapParams.center = window.ymaps.util.bounds.getCenter([leftBottom, rightTop]);
can we get the situation when window.ymaps or window.ymaps.util or window.ymaps.util.bounds is undefined?

2023-03-22 16:18 UTC, gorgeousvlad commented on src/components/Map/YMap/YandexMap.tsx
> +const DEFAULT_CENTER = [55.755864, 37.617698]; // will be calculated later
did't understand meaning of the comment

2023-03-22 16:18 UTC, gorgeousvlad commented on src/components/Map/YMap/YandexMap.tsx
> +                    className={b({visible: ready ? 'yes' : 'no'})}
`className={b({hidden: !Boolean(ready)})}`

2023-03-23 08:18 UTC, gorgeousvlad approved these changes

2023-03-23 09:08 UTC, merged