fix: change p margin for size s
gravity-ui/page-constructor pull request #29
Opened 2022-10-11 16:34 UTC by yuberdysheva

Content component with size "s" has to have margin-bottom 8px between paragraphs. 
Change a little stories for Content and ContantLayout

2022-10-12 13:21 UTC, aeksandla requested changes

2022-10-12 13:21 UTC, aeksandla commented on src/sub-blocks/Content/__stories__/Content.stories.tsx
> +import yfm from '@doc-tools/transform';
external imports should be on top

2022-10-13 11:57 UTC, yuberdysheva commented on src/sub-blocks/Content/__stories__/Content.stories.tsx
> +import yfm from '@doc-tools/transform';
fixed!

2022-10-14 12:37 UTC, aeksandla approved these changes

2022-10-14 14:43 UTC, gorgeousvlad approved these changes

2022-10-14 14:58 UTC, merged