Editor fixes pt 2
gravity-ui/page-constructor pull request #424
Opened 2023-06-22 18:49 UTC by gorgeousvlad

2023-06-22 19:25 UTC, NikitaCG requested changes

2023-06-22 19:25 UTC, NikitaCG commented on src/editor/containers/Form/Form.tsx
> +                            blocksSpec[blockData.type] && (
if there is no specification, will undefined be returned ? can we use the ternary operator to return null for security?

2023-06-23 08:11 UTC, NikitaCG approved these changes

2023-06-23 08:26 UTC, yuberdysheva approved these changes

2023-06-23 09:15 UTC, merged