feat: add content-list
gravity-ui/page-constructor pull request #468
Opened 2023-07-31 11:28 UTC by yuberdysheva

2023-08-01 15:52 UTC, NikitaCG requested changes

2023-08-01 15:52 UTC, NikitaCG commented on src/sub-blocks/Content/ContentList/ContentList.tsx
> +                    <div className={b('item')} key={title || text}>
if we dont have title or text we dont have key, and  we'll have error with this example 
`contentList = [{icon: '...'}, {icon: '...'}], {icon: '...'}]]`

2023-08-01 15:52 UTC, NikitaCG commented on src/sub-blocks/Content/Content.tsx
> +            {contentList && <ContentList contentList={contentList} size={size} />}
maybe just check the length of the array and not even render the component if it's empty?

2023-08-01 15:53 UTC, NikitaCG commented on src/sub-blocks/Content/ContentList/ContentList.tsx
> +                    <div className={b('item')} key={title || text}>
you can use `import {v4 as uuidv4} from 'uuid';` for key

2023-08-01 16:10 UTC, NikitaCG submitted a review, later dismissed

2023-08-01 17:26 UTC, gorgeousvlad requested changes

2023-08-01 17:26 UTC, gorgeousvlad commented on src/sub-blocks/Content/Content.tsx
> +            {contentList?.length && <ContentList contentList={contentList} size={size} />}
if contentList is empty array,  `0` will be rendered here

2023-08-01 17:26 UTC, gorgeousvlad commented on src/components/MediaBase/MediaBaseContent.tsx
> +                contentList={contentList}
`contentList` -> `items`

2023-08-01 17:26 UTC, gorgeousvlad commented on src/sub-blocks/Content/ContentList/ContentList.tsx
> +    contentList: ContentItemProps[];
contentList -> items

2023-08-01 18:26 UTC, gorgeousvlad commented on src/sub-blocks/Content/Content.tsx
> +            {list?.length && Boolean(list.length) && <ContentList list={list} size={size} />}
`list?.length ? <ContentList list={list} size={size} /> : null`

2023-08-02 08:14 UTC, gorgeousvlad approved these changes

2023-08-02 08:28 UTC, merged