Uikit5 (#459)
gravity-ui/page-constructor pull request #475
Opened 2023-08-02 10:08 UTC by gorgeousvlad

* feat: update to uikit-5

2023-08-02 10:43 UTC, Kyzyl-ool requested changes

2023-08-02 10:43 UTC, Kyzyl-ool commented on src/components/Button/Button.tsx
> +import {StoreBadge} from '@gravity-ui/components';
`StoreBadge` seems not to have `lang` prop and you should use `href` instead of `url`

2023-08-02 10:46 UTC, Kyzyl-ool commented on src/components/Button/Button.tsx
> +import {StoreBadge} from '@gravity-ui/components';
Oops, just saw the fix here https://github.com/gravity-ui/page-constructor/pull/476

2023-08-03 09:34 UTC, yuberdysheva approved these changes

2023-08-03 09:37 UTC, Kyzyl-ool approved these changes

2023-08-03 09:53 UTC, merged