feat(ExtendedFeatures): add content
gravity-ui/page-constructor pull request #51
Opened 2022-11-09 13:05 UTC by yuberdysheva

2022-11-09 13:48 UTC, aeksandla requested changes

2022-11-09 13:48 UTC, aeksandla commented on src/blocks/ExtendedFeatures/ExtendedFeatures.tsx
> +import {Content} from '../../sub-blocks';
need to write above

2022-11-09 13:52 UTC, gorgeousvlad approved these changes

2022-11-10 09:00 UTC, gorgeousvlad commented on src/text-transform/blocks.ts
> +        // {
remove comments

2022-11-10 11:26 UTC, aeksandla approved these changes

2022-11-10 11:29 UTC, gorgeousvlad approved these changes

2022-11-10 14:54 UTC, merged