feat: additional yfm plugins in contentTransformer
gravity-ui/page-constructor pull request #551
Opened 2023-09-11 12:28 UTC by Kyzyl-ool

2023-09-11 12:53 UTC, gorgeousvlad requested changes

2023-09-11 12:53 UTC, gorgeousvlad commented on src/text-transform/common.ts
> +    additionalPlugins: MarkdownItPluginCb[],
`additionalPlugins: MarkdownItPluginCb[] => options: {plugins: MarkdownItPluginCb[]}`

2023-09-11 12:53 UTC, gorgeousvlad commented on src/text-transform/transformers.ts
> +    additionalPlugins: MarkdownItPluginCb[],
`additionalPlugins -> options`

2023-09-11 13:37 UTC, Kyzyl-ool commented on src/text-transform/common.ts
> +    additionalPlugins: MarkdownItPluginCb[],
ready

2023-09-13 08:24 UTC, gorgeousvlad approved these changes

2023-09-18 07:05 UTC, merged