feat: add navigation
gravity-ui/page-constructor pull request #59
Opened 2022-11-22 09:46 UTC by yuberdysheva

2022-11-24 09:19 UTC, aeksandla requested changes

2022-11-24 09:19 UTC, aeksandla commented on src/components/navigation/components/MobileNavigation/MobileNavigation.tsx
> +import Foldable from '../../../Foldable/Foldable';
must be lower than external imports

2022-11-24 09:19 UTC, aeksandla commented on src/components/navigation/components/NavigationPopup/NavigationPopup.scss
> +        padding: 8px 12px;
maybe need change to indentXXXS and indentXXS

2022-11-24 09:19 UTC, aeksandla commented on src/containers/PageConstructor/PageConstructor.tsx
>  import '@doc-tools/transform/dist/js/yfm';
should be at the top

2022-11-24 09:34 UTC, gorgeousvlad requested changes

2022-11-24 09:34 UTC, gorgeousvlad commented on src/components/RouterLink/RouterLink.tsx
> +    [key: string]: any;
unknown вместо any не прокатит?

2022-11-24 09:34 UTC, gorgeousvlad commented on src/components/navigation/components/Header/Header.tsx
> +    const renderMobileMenuButton = () => {
в идеале все это сделать отдельными функциями-компонентами, можно в этом же файле

2022-11-24 09:34 UTC, gorgeousvlad commented on src/components/navigation/components/Navigation/Navigation.tsx
> +    const renderNavDropdown = (
сделать отдельной функцией

2022-11-24 09:34 UTC, gorgeousvlad commented on src/components/navigation/components/Navigation/Navigation.tsx
> +        <nav>
тоже отдельным компонентом

2022-11-24 09:34 UTC, gorgeousvlad commented on src/containers/PageConstructor/PageConstructor.tsx
> +                    {navigationData?.header && (
а где футер?

2022-11-24 09:34 UTC, gorgeousvlad commented on src/containers/PageConstructor/PageConstructor.tsx
> +                    {navigationData?.header && (
давай вынесем отрисовку навигации в отдельный компонент Layout, как это сделано на doublecloud

2022-11-24 09:34 UTC, gorgeousvlad commented on src/containers/PageConstructor/PageConstructor.tsx
> +    navigationData?: NavigationData;
`navigationData` => `navigation`

2022-11-24 09:38 UTC, aeksandla commented on src/components/navigation/components/MobileNavigation/MobileNavigation.tsx
> +                        <NavigationItem key={item.text} data={item} className={b('button')} />
the button stretched to the full width of the pop-up in the mobile version

2022-11-24 10:18 UTC, gorgeousvlad commented
please add info about navigation to readme

2022-11-29 11:06 UTC, yuberdysheva commented on src/containers/PageConstructor/PageConstructor.tsx
> +                    {navigationData?.header && (
We are waiting redesign of footer soon and we decided add footer later as other task

2022-11-30 09:05 UTC, aeksandla approved these changes

2022-12-02 08:38 UTC, gorgeousvlad commented on src/components/navigation/components/Header/Header.tsx
> +    const iconProps = {icon: isSidebarOpened ? NavigationClose : NavigationOpen, iconSize: 36};
36 сделать константой

2022-12-02 08:41 UTC, gorgeousvlad approved these changes

2022-12-02 09:19 UTC, merged