feat(Tabs): use custom tabs buttons
gravity-ui/page-constructor pull request #63
Opened 2022-11-29 12:20 UTC by yuberdysheva

2022-12-02 14:11 UTC, aeksandla requested changes

2022-12-02 14:11 UTC, aeksandla commented on src/blocks/Tabs/__stories__/data.json
> +              "text": "Button\r",
\r is not needed

2022-12-05 11:40 UTC, gorgeousvlad approved these changes

2022-12-05 11:42 UTC, niktverd approved these changes

2022-12-05 11:56 UTC, aeksandla approved these changes

2022-12-05 12:02 UTC, merged