feat(Share): create block
gravity-ui/page-constructor pull request #79
Opened 2022-12-09 09:24 UTC by yuberdysheva

2022-12-09 13:18 UTC, aeksandla approved these changes

2022-12-12 13:22 UTC, gorgeousvlad requested changes

2022-12-12 13:36 UTC, gorgeousvlad approved these changes

2022-12-12 14:31 UTC, yuberdysheva commented on src/models/constructor-items/blocks.ts
> +export enum PCShareSocialNetwork {
I didn't find this kind of enum in uikit

2022-12-12 15:26 UTC, merged