fix: shema validation
gravity-ui/page-constructor pull request #80
Opened 2022-12-09 12:55 UTC by yuberdysheva

2022-12-12 13:19 UTC, gorgeousvlad requested changes

2022-12-12 13:19 UTC, gorgeousvlad commented on src/schema/index.ts
> +    const blocksValidators = {
blockValidators

2022-12-12 13:19 UTC, gorgeousvlad commented on src/schema/index.ts
> +    const cardsValidators = {
cardValidators

2022-12-12 13:19 UTC, gorgeousvlad commented on src/schema/index.ts
> +        'simple-block',
did we delete it?

2022-12-12 13:37 UTC, yuberdysheva commented on src/schema/index.ts
> +        'simple-block',
not yet

2022-12-13 08:34 UTC, gorgeousvlad approved these changes

2022-12-13 12:55 UTC, merged