feat: screenshot testing
gravity-ui/page-constructor pull request #838
Opened 2024-02-28 13:06 UTC by niktverd

2024-02-29 15:51 UTC, NasgulNexus approved these changes

2024-03-06 10:17 UTC, gorgeousvlad requested changes

2024-03-06 10:17 UTC, gorgeousvlad commented on playwright/playwright/index.tsx
> +// import '../src/common.css';
remove line 2?

2024-03-06 10:17 UTC, gorgeousvlad commented on src/components/Anchor/__snapshots__/Anchor.visual.test.tsx-snapshots/Anchor-render-anchor-by-default-dark-chromium-linux.png
I like Malevich, maybe we should add screenshot tests for components with visual presentation?)

2024-03-06 13:14 UTC, niktverd commented on playwright/playwright/index.tsx
> +// import '../src/common.css';
ok

2024-03-06 13:16 UTC, niktverd commented on playwright/README.md
> +   > Add `defaultDelay` between mounting and testing routine in every test. It is necessary because of animation in our package.
ok

2024-03-06 13:18 UTC, niktverd commented on package.json
> +    "@playwright/experimental-ct-react": "^1.38.1",
ok

2024-03-06 13:20 UTC, niktverd commented on playwright/README.md
> +     await expectScreenshot();
the fixture inside itself makes all the arrangements to screenshot in different themes

2024-03-06 13:21 UTC, niktverd commented on src/components/Anchor/__snapshots__/Anchor.visual.test.tsx-snapshots/Anchor-render-anchor-by-default-dark-chromium-linux.png
ok

2024-03-07 13:30 UTC, Kyzyl-ool commented on playwright/playwright.config.ts
> +        /* Port to use for Playwright component endpoint. */
I think this comment is redundant

2024-03-07 13:30 UTC, Kyzyl-ool commented on src/components/Button/__snapshots__/Button.visual.test.tsx-snapshots/Button-render-stories-Default-dark-chromium-linux.png
fyi: the image is broken

2024-03-07 13:30 UTC, Kyzyl-ool commented on playwright/core/defaultDelay.ts
> +    const defaultDelay = async () => await page.waitForTimeout(DEFAULT_MOUNT_TEST_DELAY);
can we use smth like this?
```
await page.waitForLoadState('load');
```
waiting for `load` event can be more robust technique for a waiting for a page to load

2024-03-07 16:42 UTC, gorgeousvlad approved these changes

2024-03-07 17:49 UTC, merged